config/routes.rb
NpmdigitalAdmin::Engine.routes.draw do
  devise_for :users, class_name: "NpmdigitalAdmin::User", :module => :devise
  root to: 'tests#index'

  namespace :examples do
    get 'basic', to: 'basic#index'
    get 'bbgrid', to: 'bbgrid#index'
    get 'dashboard', to: 'dashboard#index'
    get 'kitchensink', to: 'kitchensink#index'
    get 'topnav', to: 'topnav#index'
    get 'sidenav', to: 'sidenav#index'
  end
end

app/models/npmdigital_admin/user.rb
module NpmdigitalAdmin
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

app/controllers/npmdigital_admin/application_controller.rb
module NpmdigitalAdmin
  class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    layout "npmdigital_admin/application_#{NpmdigitalAdmin.config.template_type}" # Template type initialized in engine or app

  end
end

app/controllers/npmdigital_admin/examples/basic_controller.rb
module NpmdigitalAdmin
  module Examples

    class BasicController < ApplicationController

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/examples/bbgrid_controller.rb
module NpmdigitalAdmin
  module Examples

    class BbgridController < ApplicationController

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/examples/dashboard_controller.rb
module NpmdigitalAdmin
  module Examples

    class DashboardController < ApplicationController

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/examples/kitchensink_controller.rb
module NpmdigitalAdmin
  module Examples

    class KitchensinkController < ApplicationController

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/examples/sidenav_controller.rb
module NpmdigitalAdmin
  module Examples

    class SidenavController < ApplicationController
      layout "npmdigital_admin/application_sidenav"

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/examples/topnav_controller.rb
module NpmdigitalAdmin
  module Examples

    class TopnavController < ApplicationController
      layout "npmdigital_admin/application_topnav"

      def index
      end

    end
  end
end

app/controllers/npmdigital_admin/tests_controller.rb
module NpmdigitalAdmin
  class TestsController < ApplicationController
    def index

    end
  end
end

app/helpers/npmdigital_admin/application_helper.rb
module NpmdigitalAdmin
  module ApplicationHelper
  end
end

app/views/layouts/npmdigital_admin/partials/_breadcrumbs.html.erb
<div class="row">
  <div class="medium-12 columns">
    <ul class="breadcrumbs">
       <%= yield :breadcrumbs %>
    </ul>
  </div>
</div>

app/views/layouts/npmdigital_admin/partials/_footer.html.erb
<footer id="mainfoot">
  <a class="credit" href="http://northpointministries.org">©<%= Time.now.year %> North Point Ministries Digital team</a>
</footer>

app/views/layouts/npmdigital_admin/partials/_header_logo.html.erb
<h1><a href="#"><%= image_tag "npmdigital_admin/npm_logo.png", class: 'npm_logo' %> <%= NpmdigitalAdmin.config.app_name %></a></h1>

app/views/layouts/npmdigital_admin/partials/_top_right_menu.html.erb
<ul class="right">
  <li class="has-dropdown">
    <a href="#"><i class="fi-torso"></i> My profile</a>
    <ul class="dropdown">
      <li><a href="#">Edit Profile</a></li>
      <li><a href="#">Workspaces</a></li>
      <li class="divider"></li>
      <li><%= link_to raw('<i class="fi-power"></i> Logout'), destroy_user_session_path, method: :delete %></li>

    </ul>
  </li>
</ul>

app/views/layouts/npmdigital_admin/sidenav/_nav.html.erb
<header id="masthead">
  <!-- Keeps navigation centered with grid. remove if you want full width of banner -->
  <div>
    <!-- / Main navigation -->
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name"><%= render 'layouts/npmdigital_admin/partials/header_logo' %></li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">

      <!-- duplicate menu here for mobile view -->
        <ul class="mobile-menu show-for-small-only">
          <li class="name"><h1><a href="#"><%= image_tag "npmdigital_admin/logo-template-24x180.png" %></a></h1></li>
          <%= render 'layouts/partials/nav' %>
        </ul>

        <%= render 'layouts/npmdigital_admin/partials/top_right_menu' %>

      </section>
    </nav>
  </div><!-- / .contain-to-grid -->

</header><!-- / #masthead -->

app/views/layouts/npmdigital_admin/sidenav/_sidenav.html.erb
<aside id="nav-container" class="visible-for-medium-up">
  <ul class="side-nav" role="navigation" title="Link List">
    <li class="name"><%= render 'layouts/npmdigital_admin/partials/header_logo' %></li>
    <%= render 'layouts/partials/nav' %>
  </ul>
</aside>

app/views/layouts/npmdigital_admin/topnav/_nav.html.erb
<header id="masthead">
  <!-- Keeps navigation centered with grid. remove if you want full width of banner -->
  <div class="contain-to-grid">
    <!-- / Main navigation -->
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <%= render 'layouts/npmdigital_admin/partials/header_logo' %>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">

      </li>
        <%= render 'layouts/npmdigital_admin/partials/top_right_menu' %>

        <!-- Left Nav Section -->
        <ul class="left">
          <li class="has-dropdown left-divider right-divider">
            <a href="#"><i class="fi-monitor"></i> Menu</a>
            <ul class="dropdown">
              <%= render 'layouts/partials/nav' %>
            </ul>
        </ul>
      </section>
    </nav>
  </div><!-- / .contain-to-grid -->

</header><!-- / #masthead -->

app/views/layouts/partials/_nav.html.erb
<li class="left-divider right-divider"><a href="<%= examples_dashboard_path %>"><i class="fi-wrench"></i> Dashboard</a></li>
<li class="left-divider right-divider"><a href="<%= examples_kitchensink_path %>"><i class="fi-wrench"></i> Kitchen Sink</a></li>
<li class="left-divider right-divider"><a href="<%= examples_bbgrid_path %>"><i class="fi-list-thumbnails"></i> bbGrid</a></li>
<li class="left-divider right-divider"><a href="<%= examples_sidenav_path %>"><i class="fi-layout"></i> Side Nav</a></li>
<li class="left-divider right-divider"><a href="<%= examples_topnav_path %>"><i class="fi-layout"></i> Top Nav</a></li>
<!-- <li><span>Has submenu</span></li>
<li class="divider"></li>
<li role="menuitem"><a href="#"><i class="fi-page"></i> Entries</a>
  <ul>
    <li><a href="#addnew"><i class="fi-plus"></i> add new</a></li>
    <li><a href="#edit"><i class="fi-pencil"></i> edit entries</a></li>
  </ul>
</li> -->

app/views/npmdigital_admin/examples/basic/index.html.erb
<% content_for :breadcrumbs do %>
  <li><a href="#">Home</a></li>
  <li><a href="#">Features</a></li>
  <li class="unavailable"><a href="#">Gene Splicing</a></li>
  <li class="current"><a href="#">Cloning</a></li>
<% end %>

<div class="row">
  <div class="medium-12 columns">

    <header>
      <h1>Child Church Name</h1>
    </header>

    <div class="panel">

      <div class="row">
        <div class="medium-12 columns">
          <header class="clearfix">
            <h2 class="left">Information</h2>
            <a class="button small right" href="#">Edit Church Info</a>
          </header>
        </div>
      </div><!--/ row -->

      <div class="row">
        <div class="medium-6 columns">

          <h4>Location</h4>
          <hr />

          <div class="row">
            <div class="medium-12 columns">

              <div class="static-field">
                <strong>Address</strong>
                <p>455 Northpoint Drive</p>
              </div><!--/static field -->

            </div><!-- /medium-12 -->
          </div><!-- / row -->

          <div class="row">
            <div class="medium-8 columns">

              <div class="static-field">
                <strong>City</strong>
                <p>Alpharetta</p>
              </div><!--/static field -->

            </div><!-- /medium-8 -->

            <div class="medium-4 columns">

              <div class="static-field">
                <strong>State</strong>
                <p>GA</p>
              </div><!--/static field -->

            </div><!-- /medium-4 -->

          </div><!-- / row -->

          <div class="row">
            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Zip Code</strong>
                <p>30322</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Country</strong>
                <p>US</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

          </div><!-- / row -->

        </div><!-- / medium-6 -->

        <div class="medium-3 columns">

          <h4>Additional Info</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>Website</strong> <br /> <span><a href="#">google.com</a></span></li>
            <li class="clearfix"><strong>Parent Organization</strong> <br /> <span>North Point Community Church</span></li>
            <li class="clearfix"><strong>Campaign end date</strong> <br /> <span>12:00pm 12/1/16</span></li>
          </ul>

        </div><!-- /4 -->

        <div class="medium-3 columns">

          <h4>Campaign Confirmation email</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>From email</strong> <br /> <span><a href="#">from@table.org</a></span></li>
            <li class="clearfix"><strong>Email Signature</strong> <br /> <span>The Children of intersect Project Team</span></li>
          </ul>

        </div><!-- /4 -->

      </div><!-- /row -->

    </div><!--/ panel -->

  </div><!--/ medium-12 -->
</div><!-- /row -->

<script>
  $(document).ready(function(){
    $('#dataTables-example').DataTable();

    // add table demo
        var i=1;
         $("#add_row").click(function(){
          $('#addr'+i).html("<td>"+ (i+1) +"</td><td><input name='name"+i+"' type='text' placeholder='Name' class='form-control input-md'  /> </td><td><input  name='mail"+i+"' type='text' placeholder='Mail'  class='form-control input-md'></td>");

          $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
          i++;
      });
       $("#delete_row").click(function(){
         if(i>1){
       $("#addr"+(i-1)).html('');
       i--;
       }
     });


  });
</script>

app/views/npmdigital_admin/examples/bbgrid/index.html.erb
<div class="row">
  <div class="medium-12 columns">
    <div class="action-panel">

      <header class="clearfix">
        <h2 class="left">
          People
        </h2>
        <a href="#" class="button right" data-reveal-id="bbModal">Create a New User</a>
      </header>

      <div id="bbModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
        <h2>Create New User</h2>
        <hr />

        <div class="row">
          <div class="small-12 small-centered columns">
              <form>
                <div class="row">
                  <div class="large-1 columns">
                    <label>Prefix
                      <select>
                        <option value="husker">Mr</option>
                        <option value="starbuck">Ms</option>
                        <option value="hotdog">Mrs</option>
                        <option value="apollo">Master</option>
                      </select>
                    </label>
                  </div>
                  <div class="large-5 columns">
                    <label>First Name
                      <input type="text" placeholder="First name" />
                    </label>
                  </div>
                  <div class="large-6 columns">
                    <label>Last Name
                      <input type="text" placeholder="Last Name" />
                    </label>
                  </div>
                </div><!--/row -->
                <div class="row">
                  <div class="large-6 columns">
                    <label>Grantee
                      <input type="text" placeholder="Sir. Church of the third Gospel of John" />
                    </label>
                  </div>
                  <div class="large-6 columns">
                    <label>Email
                      <input type="email" placeholder="jon777@aol.com" />
                    </label>
                  </div>
                </div><!--/row -->
                <div class="row">
                  <div class="large-12 columns">
                    <label>Notes (optional)
                      <textarea placeholder=""></textarea>
                    </label>
                  </div>
                </div><!--/ row -->
                <div class="row">
                  <div class="large-12 columns">
                    <div class="alert-box secondary">
                    <label>User is:</label>
                    <input type="radio" name="active" value="Red" id="inactive"><label for="inactive">inactive</label>
                    <input type="radio" name="active" value="Blue" id="active" checked><label for="active">active</label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="large-12 columns">
                    <a class="button right success" href="#">Create new user</a>
                  </div>
                </div>
              </form>
          </div>
        </div>
      <a class="close-reveal-modal" aria-label="Close"><i class="fi-x no-words"></i></a>
      </div><!-- / #bbModal -->

      <div class="content">

        <div id="bbGridSample"></div>

      </div><!--content -->

      <footer class="clearfix">
        <span class="left">You have <strong>108</strong> archived people</span>
        <a class="button secondary tiny right" href="#">View Archived users</a>
      </footer>

    </div><!-- / .action-panel -->
  </div><!--/ medium-12 -->
</div><!--/ row -->


<script>
  $(document).ready(function(){
    var app = app || {};

    app.Person = Backbone.Model.extend({});

    app.PersonCollection = Backbone.Collection.extend({
      model: app.Person,
      initialize: function( models ) {
        this.parse({})
      },
    });

    app.people = [
      {
        name: 'Ahmed Sanford',
        email: 'jon@gmail.com',
        grantee: 'Catholic Charities WV',
        status: 'Active'
      },
      {
        name: 'Tomas Budawap',
        email: 'tmas@gmail.com',
        grantee: 'Freedom Place',
        status: 'Inactive'
      },
      {
        name: 'Captian Planet',
        email: 'sludgebuster@gmail.com',
        grantee: 'The Powers Combined NW',
        status: 'Active'
      },
      {
        name: 'Spider Man',
        email: 'sixlegs@webber.com',
        grantee: 'NYC',
        status: 'Active'
      },

      {
        name: 'Audrey Hansen',
        email: 'cali@gmail.com',
        grantee: 'RESA 1',
        status: 'Inactive'
      }
    ];
    app.personCollection = new app.PersonCollection(app.people);
    app.bbGridSampleTable = new bbGrid.View({
      css: 'foundation',
      tableClass: 'responsive naked',
      container: $('#bbGridSample'),
      collection: app.personCollection,
      minimalHeader: true,
        colModel: [
          {
            property: 'name',
            label: 'Name',
            sortOrder: 'asc'
          },
          {
            property: 'email',
            label: 'E-mail'
          },
          {
            property: 'grantee',
            label: 'Grantee'
          },
          {
            property: 'status',
            label: 'Status',
            render: function(model, view) {
              return model.get('status');
            }
          },
          {
            label: 'Actions',
            sortable: false,
            width: 80,
            render: function(model, view) {
              return '<a href="#" class="button radius success tiny"><i class="fi-magnifying-glass" data-original-title="View" title="View"> </i> </a>'
                + ' <a href="#" class="button radius success tiny"><i class="fi-eye" data-original-title="Quick View" title="Quick View"> </i> </a>'
                + ' <a href="#" class="button radius success tiny"><i class="fi-pencil" data-original-title="Edit" title="Edit"> </i> </a>'
                + ' <a href="#" class="button radius alert tiny"><i class="fi-archive" data-original-title="Archive" title="Archive"> </i> </a>'
                + ' <a href="#" class="button radius alert tiny"><i class="fi-trash" data-original-title="Delete" title="Delete"> </i></a>';
            }
          }
        ],
      events: {}
    });
  });
</script>

app/views/npmdigital_admin/examples/sidenav/index.html.erb
<% content_for :breadcrumbs do %>
  <li><a href="#">Home</a></li>
  <li><a href="#">Features</a></li>
  <li class="unavailable"><a href="#">Gene Splicing</a></li>
  <li class="current"><a href="#">Cloning</a></li>
<% end %>

<div class="row">
  <div class="medium-12 columns">

    <header>
      <h1>Child Church Name</h1>
    </header>

    <div class="panel">

      <div class="row">
        <div class="medium-12 columns">
          <header class="clearfix">
            <h2 class="left">Information</h2>
            <a class="button small right" href="#">Edit Church Info</a>
          </header>
        </div>
      </div><!--/ row -->

      <div class="row">
        <div class="medium-6 columns">

          <h4>Location</h4>
          <hr />

          <div class="row">
            <div class="medium-12 columns">

              <div class="static-field">
                <strong>Address</strong>
                <p>455 Northpoint Drive</p>
              </div><!--/static field -->

            </div><!-- /medium-12 -->
          </div><!-- / row -->

          <div class="row">
            <div class="medium-8 columns">

              <div class="static-field">
                <strong>City</strong>
                <p>Alpharetta</p>
              </div><!--/static field -->

            </div><!-- /medium-8 -->

            <div class="medium-4 columns">

              <div class="static-field">
                <strong>State</strong>
                <p>GA</p>
              </div><!--/static field -->

            </div><!-- /medium-4 -->

          </div><!-- / row -->

          <div class="row">
            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Zip Code</strong>
                <p>30322</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Country</strong>
                <p>US</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

          </div><!-- / row -->

        </div><!-- / medium-6 -->

        <div class="medium-3 columns">

          <h4>Additional Info</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>Website</strong> <br /> <span><a href="#">google.com</a></span></li>
            <li class="clearfix"><strong>Parent Organization</strong> <br /> <span>North Point Community Church</span></li>
            <li class="clearfix"><strong>Campaign end date</strong> <br /> <span>12:00pm 12/1/16</span></li>
          </ul>

        </div><!-- /4 -->

        <div class="medium-3 columns">

          <h4>Campaign Confirmation email</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>From email</strong> <br /> <span><a href="#">from@table.org</a></span></li>
            <li class="clearfix"><strong>Email Signature</strong> <br /> <span>The Children of intersect Project Team</span></li>
          </ul>

        </div><!-- /4 -->

      </div><!-- /row -->

    </div><!--/ panel -->

  </div><!--/ medium-12 -->
</div><!-- /row -->

app/views/npmdigital_admin/examples/topnav/index.html.erb
<% content_for :breadcrumbs do %>
  <li><a href="#">Home</a></li>
  <li><a href="#">Features</a></li>
  <li class="unavailable"><a href="#">Gene Splicing</a></li>
  <li class="current"><a href="#">Cloning</a></li>
<% end %>

<div class="row">
  <div class="medium-12 columns">

    <header>
      <h1>Child Church Name</h1>
    </header>

    <div class="panel">

      <div class="row">
        <div class="medium-12 columns">
          <header class="clearfix">
            <h2 class="left">Information</h2>
            <a class="button small right" href="#">Edit Church Info</a>
          </header>
        </div>
      </div><!--/ row -->

      <div class="row">
        <div class="medium-6 columns">

          <h4>Location</h4>
          <hr />

          <div class="row">
            <div class="medium-12 columns">

              <div class="static-field">
                <strong>Address</strong>
                <p>455 Northpoint Drive</p>
              </div><!--/static field -->

            </div><!-- /medium-12 -->
          </div><!-- / row -->

          <div class="row">
            <div class="medium-8 columns">

              <div class="static-field">
                <strong>City</strong>
                <p>Alpharetta</p>
              </div><!--/static field -->

            </div><!-- /medium-8 -->

            <div class="medium-4 columns">

              <div class="static-field">
                <strong>State</strong>
                <p>GA</p>
              </div><!--/static field -->

            </div><!-- /medium-4 -->

          </div><!-- / row -->

          <div class="row">
            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Zip Code</strong>
                <p>30322</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

            <div class="medium-6 columns">

              <div class="static-field">
                <strong>Country</strong>
                <p>US</p>
              </div><!--/static field -->

            </div><!-- /medium-6 -->

          </div><!-- / row -->

        </div><!-- / medium-6 -->

        <div class="medium-3 columns">

          <h4>Additional Info</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>Website</strong> <br /> <span><a href="#">google.com</a></span></li>
            <li class="clearfix"><strong>Parent Organization</strong> <br /> <span>North Point Community Church</span></li>
            <li class="clearfix"><strong>Campaign end date</strong> <br /> <span>12:00pm 12/1/16</span></li>
          </ul>

        </div><!-- /4 -->

        <div class="medium-3 columns">

          <h4>Campaign Confirmation email</h4>
          <hr />
          <ul class="naked-list">
            <li class="clearfix"><strong>From email</strong> <br /> <span><a href="#">from@table.org</a></span></li>
            <li class="clearfix"><strong>Email Signature</strong> <br /> <span>The Children of intersect Project Team</span></li>
          </ul>

        </div><!-- /4 -->

      </div><!-- /row -->

    </div><!--/ panel -->

  </div><!--/ medium-12 -->
</div><!-- /row -->